### PR TITLE
Fix the Token Timeout Unusable website Issue

### LINKED ISSUE #150: When token times out page becomes unusable
when the token times out the website will continuously flash back and forth between the calendar and login pages making the website unusable.  the user must close the website and reopen it to make it usable again.  this should be fixed

### PR DESCRIPTION
**Pull request by msknobloch2**
if the token is invalid we now call logout so the data stored in session storage is cleared to prevent the flashing back and forth between login and calendar pages

closes #150

### CODE REVIEW

File: src/RefreshToken.js [hunk 1]
```diff
@@ -1,9 +1,13 @@
+import Environment from "./Components/Environment";
+
 function RefreshToken(fetchResults) {
+    var env = new Environment();
     if ("code" in fetchResults && fetchResults.code === "token_not_valid") {
-        var url = "https://recess-api.herokuapp.com/api/token/refresh/";
```
Comment (jonathanmcdaniel) [inline src/RefreshToken.js:3]: really good catch on this

**Review by jonathanmcdaniel — APPROVED** [review]

File: src/RefreshToken.js (hunk 1 above)
Comment (msknobloch2) [reply src/RefreshToken.js:3]: thanks was an improvement of opportunity

**Review by coxwm11 — APPROVED** [review]

**Review by gateship1 — APPROVED** [review]
this is a good fix
